### ISSUE TITLE
"prettier.eslintIntegration": true causes error

### ISSUE THREAD

**Issue by AndrewRayCode** [esbenp/prettier-vscode#96]
Format document with `"prettier.eslintIntegration": true` causes "Path must be a string. Received undefined". I have prettier-eslint installed in my project's node_modules directory.

**Comment by CiGit** [comment]
Does it happen on every file in your project?
We do not make use of your prettier-eslint. But prettier-eslint will try to use your installed prettier / eslint.

**Comment by Florian-R** [comment]
I can confirm this one. If I try to format with the devtools opened, I've got this error : 

```
[Extension Host] prettier-eslint [ERROR]: eslint fix failed due to an eslint error
d.logExtensionHostMessage @ extensionHost.ts:285
(anonymous) @ extensionHost.ts:139
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98

Path must be a string. Received undefined
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
(anonymous) @ mainThreadMessageService.ts:64
n.Class.derive._oncancel @ winjs.base.raw.js:1638
t.showMessage @ mainThreadMessageService.ts:34
t.$showMessage @ mainThreadMessageService.ts:28
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

After some digging, I can see, when logging the error [here](https://github.com/esbenp/prettier-vscode/blob/b3a77759c8c99e5b79d1104e3b2d16f19e6fbb57/src/PrettierEditProvider.ts#L115) that an error is thrown because of some pathname passed by eslint : 

```
[Extension Host] e TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:887:5)
    at processText (c:\Users\florian\front\dpi-osiris-angular-ui\node_modules\eslint\lib\cli-engine.js:193:30)
    at CLIEngine.executeOnText (c:\Users\f.revet\workspace\dpi-osiris-angular-ui\node_modules\eslint\lib\cli-engine.js:686:26)
    at eslintFix (C:\Users\f.revet\.vscode\extensions\esbenp.prettier-vscode-0.17.1\node_modules\prettier-eslint\dist\index.js:151:27)
    at format (C:\Users\f.revet\.vscode\extensions\esbenp.prettier-vscode-0.17.1\node_modules\prettier-eslint\dist\index.js:106:10)
    at format (C:\Users\f.revet\.vscode\extensions\esbenp.prettier-vscode-0.17.1\out\src\PrettierEditProvider.js:44:16)
    at PrettierEditProvider.provideDocumentFormattingEdits (C:\Users\f.revet\.vscode\extensions\esbenp.prettier-vscode-0.17.1\out\src\PrettierEditProvider.js:76:76)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:308630
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:73481
    at new n.Class.derive._oncancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:69530)
    at Object.f [as asWinJsPromise] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:73444)
    at e.provideDocumentFormattingEdits (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:308584)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:318379
    at t._withAdapter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:314584)
    at t.$provideDocumentFormattingEdits (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:318341)
```

Didn't go further but I'm pretty sure this error come from the fact that my current project use an old and incompatible version of eslint (1.10.3, the latest in the 1.X branch FWIW) and this extension try to use the local one.

Not sure about the way to fix that.

**Comment by CiGit** [comment]
Upgrading eslint fixes it?

**Comment by Florian-R** [comment]
Seems to fix the problem indeed.

**Comment by CiGit** [comment]
prettier-vscode 0.17.2 upgrades prettier-eslint dependency. Those it fixes this issue?
